apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Namespace}}-mongodb-secret"
type: Opaque
data:  
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "{{.Release.Namespace}}-mongodb-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}    
  {{- $mongodbpasswords := (get $secretData "mongodb-passwords") | default (randAlphaNum 8 | b64enc) }}
  mongodb-passwords: {{ $mongodbpasswords | quote }}
  {{- $mongodbrootpassword := (get $secretData "mongodb-root-password") | default (randAlphaNum 8 | b64enc) }}
  mongodb-root-password: {{ $mongodbrootpassword | quote }}
  {{- $mongodbmetricspassword := (get $secretData "mongodb-metrics-password") | default (randAlphaNum 8 | b64enc) }}
  mongodb-metrics-password: {{ $mongodbmetricspassword | quote }}
  {{- $mongodbreplicasetkey := (get $secretData "mongodb-replica-set-key") | default (randAlphaNum 8 | b64enc) }}
  mongodb-replica-set-key: {{ $mongodbreplicasetkey | quote }}