apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ivivaaccountcreation
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ivivaaccountcreation
      annotations:
        "helm.sh/hook-delete-policy": hook-succeeded,hook-failed        
    spec:
      restartPolicy: Never
      containers:      
      - name: {{ .Release.Name }}-ivivaaccountcreation
        image: iviva.azurecr.io/v4/cp-1/sdm/{{.Values.iviva.FWid}}/productapps/{{.Values.iviva.appsid}}/uxp:{{.Values.iviva.uxpid}}
        env:
          - name:  IVIVA_CONFIG_PATH
            value: /iviva/config/ivivaconfig.yaml        
        volumeMounts:
          - name:  {{ .Values.iviva.releasename }}-ivivaconfig
            mountPath:  /iviva/config
          - name:  {{ .Values.iviva.releasename }}-ivivaaccountcreationlogs
            mountPath:  /var/log/iviva
        command: ["/bin/bash", "-c"]
        args:
          - apt-get update && apt-get install -y git;
            cd /iviva/;
            git clone https://{{.Values.iviva.gitpersonalaccesstoken}}@{{.Values.iviva.giturl}};
            cd mda-account-creation;
            /iviva/sdm/sdm newaccount  {{ .Values.iviva.accountname }} ./profile.xml LoginID {{ .Values.iviva.accountusername }} Password {{ .Values.iviva.accountpassword }} FirstName {{ .Values.iviva.accountfirstname }} LastName {{ .Values.iviva.accountlastname }} Email {{ .Values.iviva.accountemailid }};
            /iviva/sdm/sdm {{ .Values.iviva.accountname }} importmodelsettings ./model-settings.json;
            /iviva/sdm/sdm broadcast config/reset
      volumes:
        - name: {{ .Values.iviva.releasename }}-ivivaconfig
          configMap: 
            name: {{ .Values.iviva.releasename }}-ivivaconfig
            defaultMode : 0777
        - name: {{ .Values.iviva.releasename }}-ivivaaccountcreationlogs
          emptyDir: {}
      imagePullSecrets:
      - name: azure-reg-pull