
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ivivasdm
spec:
  replicas: {{ .Values.iviva.sdmpodscount}}
  strategy:
        type: {{ .Values.deployment.type }}
        rollingUpdate:
           maxSurge: {{ .Values.deployment.maxSurge}}
           maxUnavailable: {{ .Values.deployment.maxUnavailable}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ivivasdm
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ivivasdm
    spec:
      containers:      
      - name: {{ .Release.Name }}-ivivasdm
        image: iviva.azurecr.io/v4/cp-1/sdm/{{.Values.iviva.FWid}}/productapps/{{.Values.iviva.appsid}}/uxp:{{.Values.iviva.uxpid}}
        resources:
          requests:
            memory: {{ .Values.memrequests.sdm}}
            cpu: {{ .Values.cpurequests.sdm}}
          limits:
            memory: {{ .Values.memlimits.sdm}}
            cpu: {{ .Values.cpulimits.sdm}} 
        env:
          - name:  IVIVA_CONFIG_PATH
            value: /iviva/config/ivivaconfig.yaml        
          - name: LUCYENGINE_HTTPSERVER_HOST
            value: {{.Release.Name}}-lucyengineprimary
          - name: LUCYENGINE_HTTPSERVER_PORT
            value: "9111"
        volumeMounts:
          - name:  {{ .Release.Name }}-ivivaconfig
            mountPath:  /iviva/config
          - name:  {{ .Release.Name }}-ivivasdmlogs
            mountPath:  /var/log/iviva
        command: ["tail"]
        args:
          - "-f"
          - "/dev/null"
      restartPolicy: Always

      volumes:
        - name: {{ .Release.Name }}-ivivaconfig
          configMap: 
            name: {{ .Release.Name }}-ivivaconfig
            defaultMode : 0777
        - name: {{ .Release.Name }}-ivivasdmlogs
          emptyDir: {}
      imagePullSecrets:
      - name: azure-reg-pull
      




