apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ivivasdtaskrunner
spec:
  replicas: {{ .Values.iviva.sdtaskrunnerpodscount}}
  strategy:
        type: {{ .Values.deployment.type }}
        rollingUpdate:
           maxSurge: {{ .Values.deployment.maxSurge}}
           maxUnavailable: {{ .Values.deployment.maxUnavailable}} 
  selector:  
    matchLabels:
      app: {{ .Release.Name }}-ivivasdtaskrunner
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ivivasdtaskrunner
    spec:
      containers:      
      - name: {{ .Release.Name }}-ivivasdtaskrunner
        image: iviva.azurecr.io/v4/cp-1/jobrunner/{{.Values.iviva.FWid}}/productapps/{{.Values.iviva.appsid}}/uxp:{{.Values.iviva.uxpid}}
        resources:
          requests:
            memory: {{ .Values.memrequests.sdtaskrunner}}
            cpu: {{ .Values.cpurequests.sdtaskrunner}}
          limits:
            memory: {{ .Values.memlimits.sdtaskrunner}}
            cpu: {{ .Values.cpulimits.sdtaskrunner}} 
        env:
          - name:  IVIVA_CONFIG_PATH
            value: /iviva/config/ivivaconfig.yaml
          - name: LUCYENGINE_HTTPSERVER_HOST
            value: {{.Release.Name}}-lucyengineprimary   
          - name: LUCYENGINE_HTTPSERVER_PORT
            value: "9111" 
        volumeMounts:
          - name:  {{ .Release.Name }}-ivivaconfig
            mountPath:  /iviva/config
          - name:  {{ .Release.Name }}-ivivasdtaskrunnerlogs
            mountPath:  /var/log/iviva
      restartPolicy: Always

      volumes:
        - name: {{ .Release.Name }}-ivivaconfig
          configMap: 
            name: {{ .Release.Name }}-ivivaconfig
            defaultMode : 0777
        - name: {{ .Release.Name }}-ivivasdtaskrunnerlogs
          emptyDir: {}
      imagePullSecrets:
      - name: azure-reg-pull
      




